name: CI

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3
      with:
        path: 'breaking-bad-ds'
    - name: 'Checkout libfilesystem'
      uses: actions/checkout@v3
      with:
        repository: 'RetroVNDjinn/libfilesystem'
        path: 'libfilesystem'
    - name: 'Patch libfilesystem'
      run: |
        cd ./libfilesystem;
        make;
        cp ./lib/libfilesystem.a /opt/devkitpro/libnds/lib/libfilesystem.a;
        cd ../;
    - name: 'Checkout Nitro-Engine'
      uses: actions/checkout@v3
      with:
        repository: 'AntonioND/nitro-engine'
        path: 'nitro-engine'
    - name: 'Build Nitro-Engine'
      run: |
        cd ./nitro-engine;
        make;
        cd ../;
        cp -r ./nitro-engine /opt/devkitpro/nitro-engine;
    - name: 'Checkout NightFoxLib'
      uses: actions/checkout@v3
      with:
        repository: 'knightfox75/nds_nflib'
        path: 'nds_nflib'
    - name: 'Build NightFoxLib'
      run: |
        cd ./nds_nflib;
        make;
        cd ../;
        cp -r ./nds_nflib /opt/devkitpro/nflib;
    - name: 'Execute build'
      run: |
        cd ./breaking-bad-ds/
        make;
    - name: 'Upload ROM'
      uses: actions/upload-artifact@v3
      with:
        path: |
           ./breaking-bad-ds/*.nds
           ./breaking-bad-ds/*.md
           ./breaking-bad-ds/LICENSE
           ./breaking-bad-ds/cover-artwork.png
        name: 'Breaking Bad DS'
